const colors = {
  light: {
    text: '#1C1C1E',
    tint: '#007AFF',
    background: '#FFFFFF',
    foreground: '#1C1C1E',
    card: '#F2F2F7',
    cardForeground: '#1C1C1E',
    primary: '#007AFF',
    primaryForeground: '#FFFFFF',
    secondary: '#F2F2F7',
    secondaryForeground: '#1C1C1E',
    muted: '#F2F2F7',
    mutedForeground: '#8E8E93',
    accent: '#007AFF',
    accentForeground: '#FFFFFF',
    destructive: '#FF3B30',
    destructiveForeground: '#FFFFFF',
    border: '#E5E5EA',
    input: '#E5E5EA',
    success: '#34C759',
    warning: '#FF9500',
  },
  dark: {
    text: '#FFFFFF',
    tint: '#0A84FF',
    background: '#1C1C1E',
    foreground: '#FFFFFF',
    card: '#2C2C2E',
    cardForeground: '#FFFFFF',
    primary: '#0A84FF',
    primaryForeground: '#FFFFFF',
    secondary: '#3A3A3C',
    secondaryForeground: '#FFFFFF',
    muted: '#3A3A3C',
    mutedForeground: '#8E8E93',
    accent: '#0A84FF',
    accentForeground: '#FFFFFF',
    destructive: '#FF453A',
    destructiveForeground: '#FFFFFF',
    border: '#38383A',
    input: '#38383A',
    success: '#30D158',
    warning: '#FF9F0A',
  },
  radius: 12,
};

export default colors;
